# Generated by Django 2.0.6 on 2018-06-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.IntegerField(choices=[('Facebook', 'Facebook'), ('Email', 'Email'), ('Phone', 'Phone')]),
        ),
    ]
