# Generated by Django 2.0.6 on 2018-07-06 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0002_auto_20180627_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Email', 'Email'), ('Phone', 'Phone')],
                                   max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='branches',
            field=models.ManyToManyField(related_name='Courses', to='system.Branch'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Courses',
                                    to='system.Category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='contacts',
            field=models.ManyToManyField(related_name='Courses', to='system.Contact'),
        ),
    ]
