# Generated by Django 2.0.6 on 2018-07-06 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0003_auto_20180706_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='altitude',
            new_name='latitude',
        ),
    ]
